waveform_params:

  channels: "AE"
  modes: [[2,2]]
  noise: "sangria"
  duration: 1 # weeks
  dt: 100 # seconds

prior:
  "logMchirp": [5, 6] # log10(Mchirp/Msun)
  "q": [1, 5]
  "chi1": [0,0]
  "chi2": [0,0]
  "dist": [4.0,40]  # dist in Gpc (note that we shall sample uniformly dist^3)
  "phi": [0.0, 6.28318530718]
  "inc": [-1.0 ,1.0]
  "lambda": [0.0, 6.28318530718]
  "beta": [-1.0, 1.0] # sin beta
  "psi": [0.0, 3.14159265358979]
  "Deltat": [ -3, -1 ] # t_merger from end of observation in days

training: 
  batch_size: 100
  epochs: 1000
  learning_rate: 0.0001
  transform_td: "normalise_max" # options: "none", "logwhiten", "log", "whiten"
  transform_fd: "log" # options: "none", "logwhiten", "log", "whiten", "normalise_max"
  early_stop_patience: 30
  scheduler_factor: 0.3
  scheduler_patience: 10
  
tmnre:
  marginals: 
    t: [[10]]

device: "cuda"