waveform_params:

  channels: "AE"
  modes: [[2,2]]
  noise: "sangria"
  duration: 1 # weeks
  min_freq: -4 # log10(f/Hz)
  max_freq: -2 # log10(f/Hz)
  n_freqs: 10000 # number of frequency bins in the waveform
  
prior:
  "logMchirp": [5, 6] # log10(Mchirp/Msun)
  "q":  [1, 5]
  "chi1": [0,0]
  "chi2": [0,0]
  "dist": [4.0,40]  # dist in Gpc (note that we shall sample uniformly dist^3)
  "phi": [0.0, 6.28318530718]
  "inc": [-1.0 ,1.0] # cos inclination
  "lambda": [0.0, 6.28318530718]
  "beta": [-1.0, 1.0] # sin beta
  "psi": [0.0, 3.14159265358979]
  "Deltat": [ 0, 0 ] # t_merger from end of observation in days

training: 
  batch_size: 100
  epochs: 1000
  learning_rate: 0.01
  transform: "log" # options: "none", "logwhiten", "log", "whiten"
  scheduler_factor: 0.2
  scheduler_patience: 50
  early_stop_patience: 75
tmnre:
  marginals: [[0], [1], [0,1]]