waveform_params:

  TDI: "AE"
  modes: [[2,2]]
  noise: "sangria"
  duration: 4 # weeks
  
prior:
  "logMchirp": [5,6] # log10(Mchirp/Msun)
  "q": [1.0,5.0]
  "chi1": [0,0]
  "chi2": [0,0]
  "dist": [4.0,40]  # dist in Gpc (note that we shall sample uniformly dist^3)
  "phi": [0.0, 6.28318530718]
  "inc": [-1.0 ,1.0]
  "lambda": [0.0, 6.28318530718]
  "beta": [-1.0, 1.0] # sin beta
  "psi": [0.0, 3.14159265358979]
  "Deltat": [ 3, 3 ] # t_merger from end of observation in days

training: 
  batch_size: 100
  epochs: 1000
  learning_rate: 0.001
  transform: "log" # options: "none", "logwhiten", "log", "whiten"

tmnre:
  marginals: [[0], [1], [0,1]]