"""Augment an existing observation HDF5 file with a fixed noise realisation.

The training-time observation must contain a *stored* noise realisation so
that ``PlotPosteriorCallback``, ``visualise_truncation_rounds.py`` and any
deployment all see the same signal+noise combination.  Existing observation
files generated by older runs of ``MBHBSimulatorFD.sample_and_store`` only
contain pure ``wave_fd``; this script reads such a file, draws a single
seeded noise realisation per sample using the stored ``asd`` / ``df`` /
``frequencies``, and writes a new HDF5 file containing every original
dataset plus a ``noise_fd`` array of identical shape to ``wave_fd``.

Noise colouring matches ``mbhb_collate_fn``:
    noise_fd = (CN(0,1) * filtered_asd) / sqrt(4 * df)
where ``filtered_asd`` zeros bins below ``FMIN_FLOOR`` Hz.

Usage
-----
    /data/gpuleo/envs/lisa_pip/bin/python scripts/add_noise_to_obs.py \
        --input  /data/gpuleo/mbhb/obs_logfreq_q3_t.h5 \
        --output /data/gpuleo/mbhb/obs_logfreq_q3_t_noisy.h5 \
        --seed   0
"""

import argparse
import os

import h5py
import numpy as np

from pembhb import FMIN_FLOOR


def add_noise_to_obs(input_path: str, output_path: str, seed: int = 0,
                     overwrite: bool = False) -> None:
    if os.path.abspath(input_path) == os.path.abspath(output_path):
        raise ValueError("input_path and output_path must differ")
    if os.path.exists(output_path) and not overwrite:
        raise FileExistsError(
            f"{output_path} already exists. Pass --overwrite to replace it."
        )

    with h5py.File(input_path, "r") as src:
        if "noise_fd" in src:
            print(f"[add_noise] {input_path} already contains 'noise_fd' — "
                  f"the new file will overwrite it with a fresh seeded draw.")

        wave_fd = src["wave_fd"][()]                # (N, n_ch, n_freqs)
        asd = src["asd"][()]                        # (n_ch, n_freqs)
        freqs = src["frequencies"][()]              # (n_freqs,)

        T = float(src.attrs["observation_duration_SI"])

        N, n_ch, n_freqs = wave_fd.shape
        assert asd.shape == (n_ch, n_freqs), "asd shape inconsistent with wave_fd"

        # Filtered ASD: zero out bins below the high-pass cutoff so noise
        # there is exactly zero, mirroring mbhb_collate_fn's noise_scale.
        filtered_asd = asd.copy()
        filtered_asd[:, freqs < FMIN_FLOOR] = 0.0

        # noise_scale = filtered_asd / sqrt(4 * df) — same formula as collate fn
        noise_scale = filtered_asd / np.sqrt(4.0  / T)   # (n_ch, n_freqs)

        rng = np.random.default_rng(seed)
        re = rng.standard_normal(size=(N, n_ch, n_freqs)).astype(asd.dtype)
        im = rng.standard_normal(size=(N, n_ch, n_freqs)).astype(asd.dtype)
        z = re + 1j * im
        noise_fd = (z * noise_scale[None, :, :]).astype(wave_fd.dtype)

        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with h5py.File(output_path, "w") as dst:
            for k in src.keys():
                if k == "noise_fd":
                    continue   # we'll write our own below
                src.copy(k, dst)
            for ak, av in src.attrs.items():
                dst.attrs[ak] = av
            dst.create_dataset("noise_fd", data=noise_fd)
            dst.attrs["noise_seed"] = int(seed)

    # Copy the YAML sidecar (if any) so the new obs file has the same metadata.
    src_yaml = input_path[:-3] + ".yaml" if input_path.endswith(".h5") else input_path + ".yaml"
    if os.path.exists(src_yaml):
        dst_yaml = output_path[:-3] + ".yaml" if output_path.endswith(".h5") else output_path + ".yaml"
        with open(src_yaml, "r") as fin, open(dst_yaml, "w") as fout:
            fout.write(fin.read())
        print(f"[add_noise] Copied YAML sidecar -> {dst_yaml}")

    print(f"[add_noise] Wrote {output_path}")
    print(f"[add_noise]   N={N}, n_channels={n_ch}, n_freqs={n_freqs}, seed={seed}")
    print(f"[add_noise]   noise_fd dtype={noise_fd.dtype}, "
          f"|noise|_max={np.max(np.abs(noise_fd)):.3e}")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", required=True,
                   help="Path to the existing pure-signal obs HDF5 file.")
    p.add_argument("--output", required=True,
                   help="Path for the new HDF5 file (must differ from --input).")
    p.add_argument("--seed", type=int, default=0,
                   help="RNG seed for the noise draw (default: 0).")
    p.add_argument("--overwrite", action="store_true",
                   help="Overwrite --output if it already exists.")
    args = p.parse_args()

    add_noise_to_obs(args.input, args.output, seed=args.seed,
                     overwrite=args.overwrite)
